"""
Explanation service for the AI-Driven Promotion and Inventory Planner.

Builds a structured explanation for a single (item_id, store_id) pair by
reading the recommendation document that was already generated by the
rule-based engine in src/recommendations/generate_recommendations.py and
the corresponding product document from the products collection.

IMPORTANT LABELS (inherited from generate_recommendations.py):
- Demand: average_daily_units is a HISTORICAL PROXY, not an ML forecast.
  If demand_source starts with 'BACKTEST', it is a prototype RF backtest
  average over the 28 test days -- still not a live forecast.
- Inventory: SIMULATED (seed=42, coverage 3-45 days; not real stock data).
- Unit cost: ASSUMED (cost ratio = 0.7 x selling price; not actual data).
- Thresholds used by the rule engine are PROTOTYPE ASSUMPTIONS.
- No promotion lift is estimated. A candidate discount is a suggestion for
  human review only.
- This service is rule-based. It is NOT a generative AI or LLM.

All explanation text is derived from fields already stored in MongoDB; no
new rule logic is re-implemented here. The service reads and reformats the
stored explanation text and numeric fields to produce structured output.
"""

import math
from typing import Optional

# ---------------------------------------------------------------------------
# Constants mirrored from generate_recommendations.py (for reference only --
# the rule was already applied at data-generation time and results are stored
# in MongoDB).
# ---------------------------------------------------------------------------
_LOW_COVERAGE_DAYS = 7
_HIGH_COVERAGE_DAYS = 30
_PROMO_MIN_COVERAGE_DAYS = 14
_DECLINE_PCT_THRESHOLD = 20.0
_MIN_PREV_UNITS = 10
_MIN_MARGIN_PCT = 5.0
_CANDIDATE_DISCOUNTS = [0, 5, 10, 15]       # percent
_EXCESS_DISCOUNT_TIERS = [(30, 5), (35, 10), (40, 15)]
_DECLINE_CANDIDATE_DISCOUNT = 5


def _safe_float(value) -> Optional[float]:
    """Return None if value is None, NaN, or infinite; otherwise a float."""
    if value is None:
        return None
    try:
        f = float(value)
    except (TypeError, ValueError):
        return None
    if math.isnan(f) or math.isinf(f):
        return None
    return f


def _safe_int(value) -> Optional[int]:
    """Return None if value cannot be safely converted to int."""
    f = _safe_float(value)
    return int(round(f)) if f is not None else None


def _demand_label(demand_source: Optional[str]) -> str:
    """Summarise the demand source in one short phrase."""
    if not demand_source:
        return "unknown source"
    s = demand_source.upper()
    if "BACKTEST" in s:
        return "prototype RF backtest average (not a live forecast)"
    return "historical proxy (not a live forecast)"


def _discount_scenario(rec_doc: dict, discount_pct: int) -> Optional[dict]:
    """
    Extract one discount scenario from the recommendation document.
    Returns None if the price field is missing for this tier.
    """
    price = _safe_float(rec_doc.get(f"price_disc_{discount_pct}"))
    margin = _safe_float(rec_doc.get(f"unit_margin_disc_{discount_pct}"))
    margin_pct = _safe_float(rec_doc.get(f"margin_pct_disc_{discount_pct}"))
    valid = rec_doc.get(f"valid_disc_{discount_pct}")
    if price is None:
        return None
    return {
        "discount_pct": discount_pct,
        "discounted_price": price,
        "unit_margin": margin,
        "margin_pct": margin_pct,
        "passes_margin_rules": bool(valid) if valid is not None else None,
    }


def build_explanation(product_doc: dict, rec_doc: dict) -> dict:
    """
    Build a structured explanation for one (item_id, store_id) pair.

    Parameters
    ----------
    product_doc:
        One document from the ``products`` collection (promotion_inputs.csv
        fields).
    rec_doc:
        One document from the ``recommendations`` collection
        (promotion_recommendations.csv fields).

    Returns
    -------
    dict with the structure documented in the API spec.
    """
    item_id = rec_doc.get("item_id") or product_doc.get("item_id")
    store_id = rec_doc.get("store_id") or product_doc.get("store_id")

    # ------------------------------------------------------------------
    # Core recommendation fields (from recommendations collection)
    # ------------------------------------------------------------------
    recommendation = rec_doc.get("recommendation")
    stored_explanation = rec_doc.get("explanation")
    selected_discount = _safe_float(rec_doc.get("selected_candidate_discount_pct"))
    # 0.0 means "no discount selected" in the engine output
    selected_discount_pct = (
        _safe_int(selected_discount)
        if selected_discount is not None and selected_discount > 0
        else None
    )
    selected_discounted_price = _safe_float(rec_doc.get("selected_discounted_price"))
    selected_margin_pct = _safe_float(rec_doc.get("selected_discounted_margin_pct"))
    data_labels = rec_doc.get("data_labels")

    # ------------------------------------------------------------------
    # Demand metrics
    # ------------------------------------------------------------------
    demand_source_raw = rec_doc.get("demand_source")
    demand_used = _safe_float(rec_doc.get("demand_used_units_per_day"))
    # Products collection carries the two 28-day windows
    previous_28d = _safe_float(product_doc.get("previous_28d_units"))
    recent_28d = _safe_float(product_doc.get("recent_28d_units"))
    demand_change_pct = _safe_float(
        rec_doc.get("demand_change_pct")
        if rec_doc.get("demand_change_pct") is not None
        else product_doc.get("demand_change_pct")
    )

    # ------------------------------------------------------------------
    # Inventory metrics (SIMULATED)
    # ------------------------------------------------------------------
    simulated_stock = _safe_float(rec_doc.get("simulated_inventory_units"))
    coverage_days = _safe_float(rec_doc.get("coverage_days"))
    inventory_source = product_doc.get("inventory_source")

    # ------------------------------------------------------------------
    # Price / cost / margin (current, at full price)
    # ------------------------------------------------------------------
    sell_price = _safe_float(rec_doc.get("latest_sell_price"))
    assumed_cost = _safe_float(rec_doc.get("assumed_unit_cost"))
    cost_source = product_doc.get("cost_source")
    current_unit_margin = _safe_float(rec_doc.get("current_unit_margin"))
    current_margin_pct = _safe_float(rec_doc.get("current_margin_pct"))

    # ------------------------------------------------------------------
    # Rejected scenarios
    # ------------------------------------------------------------------
    rejected_scenarios_raw = rec_doc.get("rejected_scenarios")
    rejected_scenarios = (
        rejected_scenarios_raw
        if isinstance(rejected_scenarios_raw, str) and rejected_scenarios_raw.strip()
        else None
    )

    # ------------------------------------------------------------------
    # All four discount scenarios (0, 5, 10, 15 %)
    # ------------------------------------------------------------------
    discount_scenarios = []
    for d in _CANDIDATE_DISCOUNTS:
        scenario = _discount_scenario(rec_doc, d)
        if scenario is not None:
            discount_scenarios.append(scenario)

    # ------------------------------------------------------------------
    # Supporting factors -- derived from which rule fired, not re-computed
    # ------------------------------------------------------------------
    supporting_factors = []

    if coverage_days is not None:
        if coverage_days >= _HIGH_COVERAGE_DAYS:
            supporting_factors.append(
                f"Simulated stock coverage is {coverage_days:.1f} days, at or above the "
                f"prototype excess threshold of {_HIGH_COVERAGE_DAYS} days."
            )
        elif coverage_days < _LOW_COVERAGE_DAYS:
            supporting_factors.append(
                f"Simulated stock coverage is {coverage_days:.1f} days, below the "
                f"prototype low-stock threshold of {_LOW_COVERAGE_DAYS} days."
            )
        else:
            supporting_factors.append(
                f"Simulated stock coverage is {coverage_days:.1f} days, between the "
                f"prototype thresholds of {_LOW_COVERAGE_DAYS} and {_HIGH_COVERAGE_DAYS} days."
            )

    if demand_change_pct is not None and previous_28d is not None and previous_28d >= _MIN_PREV_UNITS:
        if demand_change_pct <= -_DECLINE_PCT_THRESHOLD:
            supporting_factors.append(
                f"Recent 28-day units fell {abs(demand_change_pct):.1f}% versus the previous "
                f"28 days (prototype decline threshold: -{_DECLINE_PCT_THRESHOLD:g}%)."
            )
        else:
            supporting_factors.append(
                f"Recent 28-day units changed {demand_change_pct:+.1f}% versus the previous "
                f"28 days (prototype decline threshold: -{_DECLINE_PCT_THRESHOLD:g}%; "
                "threshold not met)."
            )
    elif demand_change_pct is None:
        supporting_factors.append(
            "Demand-change percentage could not be computed (previous-period units unavailable "
            f"or previous 28-day units below the {_MIN_PREV_UNITS}-unit minimum required by "
            "the rule engine)."
        )

    if selected_discount_pct is not None:
        supporting_factors.append(
            f"A {selected_discount_pct}% candidate discount was selected as the largest discount "
            f"that satisfies the minimum margin rule (>= {_MIN_MARGIN_PCT:g}% after discount) "
            "and fits within the applicable coverage-tier cap."
        )
    elif recommendation and "blocked" in recommendation.lower():
        supporting_factors.append(
            "All non-zero candidate discounts were blocked by the margin rules or no tier applies. "
            + (f"Details: {rejected_scenarios}." if rejected_scenarios else "")
        )

    # ------------------------------------------------------------------
    # Data limitations
    # ------------------------------------------------------------------
    limitations = [
        "Demand is a HISTORICAL PROXY (average_daily_units from the M5 dataset). "
        "It is not a live forecast and does not predict future sales.",
        "Inventory (simulated_inventory_units) is SIMULATED with a fixed seed and "
        "does not represent actual Walmart stock levels.",
        "Unit cost is ASSUMED at 0.7x the selling price. It is not actual Walmart cost data.",
        "All coverage thresholds and discount tiers are PROTOTYPE ASSUMPTIONS, not tuned or validated.",
        "No promotion-lift estimate is made. A candidate discount is a suggestion for human review only.",
        "This explanation is generated by a rule-based engine, not by an LLM or generative AI model.",
    ]
    if demand_source_raw and "BACKTEST" in demand_source_raw.upper():
        limitations.insert(
            0,
            "Demand used here is a PROTOTYPE backtest average of Random Forest predictions over the "
            "28-day test window. It is not a live or future forecast.",
        )

    # ------------------------------------------------------------------
    # Assemble result
    # ------------------------------------------------------------------
    return {
        "item_id": item_id,
        "store_id": store_id,
        "category": rec_doc.get("cat_id") or product_doc.get("cat_id"),
        "department": rec_doc.get("dept_id") or product_doc.get("dept_id"),
        "recommendation": recommendation,
        "selected_candidate_discount_pct": selected_discount_pct,
        "selected_discounted_price": selected_discounted_price,
        "selected_discounted_margin_pct": selected_margin_pct,
        "explanation": stored_explanation,
        "supporting_factors": supporting_factors,
        "demand_metrics": {
            "demand_used_units_per_day": demand_used,
            "demand_source": demand_source_raw,
            "demand_label": _demand_label(demand_source_raw),
            "previous_28d_units": _safe_int(previous_28d),
            "recent_28d_units": _safe_int(recent_28d),
            "demand_change_pct": demand_change_pct,
        },
        "inventory_metrics": {
            "simulated_inventory_units": _safe_int(simulated_stock),
            "coverage_days": coverage_days,
            "inventory_source": inventory_source,
        },
        "price_and_margin": {
            "latest_sell_price": sell_price,
            "assumed_unit_cost": assumed_cost,
            "cost_source": cost_source,
            "current_unit_margin": current_unit_margin,
            "current_margin_pct": current_margin_pct,
        },
        "discount_scenarios": discount_scenarios,
        "rejected_discount_scenarios": rejected_scenarios,
        "data_labels": data_labels,
        "data_limitations": limitations,
    }
